spring:
  application:
    name: banking-apps
  datasource:
#    url: ${DB_URL}
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: anggara123
    url: jdbc:postgresql://localhost:5432/bank-application
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: inikel6synrgy@gmail.com
    password: qawt suac pqze hsar
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8081
  servlet:
    context-path: /api/v1.0
security:
  jwt:
#    secret-key: ${JWT_SECRET_KEY}
    secret-key: eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTcyMTk5ODYyOCwiaWF0IjoxNzIxOTk4NjI4fQ.mCpurlvVlvF5Lx99H-NC_ZtGl0XtJsbihFS4z4I2aiE
#    expired-milliseconds: ${JWT_EXPIRED_MILLISECONDS}
    expired-milliseconds: 123131231421123
#    transaction-secret-key: ${JWT_TRANSACTION_SECRET_KEY}
    transaction-secret-key: eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTcyMTk5ODYyOCwiaWF0IjoxNzIxOTk4NjI4fQ.mCpurlvVlvF5Lx99H-NC_ZtGl0XtJsbihFS4z4I2aiE
#    transaction-expired-milliseconds: ${JWT_TRANSACTION_EXPIRED_MILLISECONDS}
    transaction-expired-milliseconds: 123131231421123